### ISSUE TITLE
Lost all my money, refund please

### ISSUE THREAD

**Issue by Entalpi** [aeakoski/market_analyser#1]
Hello,
I used this program to invest all my financial assets (and my familys). It predicted to buy some stocks, I bought all the stocks. Now the stocks are worth less than a stick of gum :-1: . Such bad investment. Wow. Much sadness. So financial ruin. Refund plz. 

Thx

**Comment by aeakoski** [comment]
Hello, 
This is expected behaviour, it is a feature not a bug. Enjoy new more simpler life. No refunds. 

Best regards
